name: Node.js CI/CD with SAST  # Name of the GitHub Actions workflow

on:  # Defines workflow triggers
  push:  # Runs when code is pushed
    branches: 
      - main  # Only triggers when pushing to 'main' branch
      - '*'   # Triggers on all other branches (except main)
  pull_request:  # Runs when a pull request is opened
    branches:
      - '*'   # Triggers on all branches

permissions:
  contents: read
  security-events: write  # ✅ Allows CodeQL to upload SARIF results

jobs:  

  security_scan:  # Job to perform Static Application Security Testing (SAST)
    if: github.ref == 'refs/heads/main'  # Run only if code is pushed to 'main'
    name: Security Scan (SAST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository  # Step 1: Fetch the latest code
        uses: actions/checkout@v4

      - name: Initialize CodeQL  # Step 2: Set up CodeQL for security scanning
        uses: github/codeql-action/init@v3
        with:
          autodetect: true  # ✅ Auto-detect available languages
      - name: Perform CodeQL Analysis  # Step 3: Run the security analysis
        uses: github/codeql-action/analyze@v3

  build:  # Job to build and test the application
    needs: security_scan  # Waits for security scan if it runs (otherwise continues)
    if: success() || needs.security_scan.result == 'skipped'  # Runs if scan passes or is skipped
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository  # Step 1: Fetch the latest code
        uses: actions/checkout@v4

      - name: Setup Node.js  # Step 2: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version

      - name: Install dependencies  # Step 3: Install project dependencies
        run: npm install

      - name: Run tests  # Step 4: Execute tests
        run: npm test
